[package]
name = "batteria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
batteria-cli = { path = "./batteria-cli" }
clap = { version = "4.0.23", features = ["derive"] }
battery = "0.7.8"
